name: 'Update Check Run'
description: "Update a GitHub Check Run's status"

inputs:
  sha:
    description: 'The SHA of the commit to update the check for'
    required: true
  name:
    description: 'The name of the check run to update'
    required: true
  status:
    description: 'The new status of the check run (in_progress, completed)'
    required: false
  conclusion:
    description: 'The final result of the check run (success, failure, cancelled, etc)'
    required: false
  title:
    description: "Title for the check run's output"
    required: false
  summary:
    description: "Summary text for the check run's output"
    required: false
  details_url:
    description: 'Optional URL with more information about the check'
    required: false
  token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: 'node20'
  main: 'dist/index.mjs'
